"""Configuration wizard for notewise."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any, Protocol

from notewise._constants import (
    AUTH_TYPE_API_KEY,
    AUTH_TYPE_OAUTH_DEVICE,
    CONFIG_FILENAME,
    DEFAULT_MAX_CONCURRENT_VIDEOS,
    DEFAULT_OUTPUT_DIR,
    OAUTH_SETUP_RUN_PROMPT,
    PROVIDER_CONFIG,
)
from notewise._constants import (
    LEGACY_CONFIG_KEYS as APP_LEGACY_CONFIG_KEYS,
)
from notewise.config import get_state_dir
from notewise.errors import ConfigurationError
from notewise.model_catalog import (
    classify_provider,
    get_model_metadata,
    is_setup_safe_model,
    load_model_snapshot,
    normalize_available_models,
)
from notewise.utils import mask_secret, parse_config_env_lines


if TYPE_CHECKING:
    from rich.console import Console


class RunOAuthLoginProto(Protocol):
    """Callable signature for the lazily imported OAuth login helper."""

    def __call__(self, provider: str, *, console: Console | None = None) -> bool: ...


LEGACY_CONFIG_KEYS = set(APP_LEGACY_CONFIG_KEYS)
run_oauth_login: RunOAuthLoginProto | None = None


def _load_oauth_dependencies() -> None:
    """Populate OAuth login helpers lazily."""
    global run_oauth_login

    if run_oauth_login is None:
        from notewise.ui.oauth_flow import run_oauth_login as _run_oauth_login

        run_oauth_login = _run_oauth_login


def _resolve_console(console: Console | None) -> Console:
    """Return the provided console or create a fresh one for this flow."""
    from rich.console import Console

    return console if console is not None else Console()


def _normalize_available_models(
    provider_models: dict[str, list[str]],
) -> dict[str, list[str]]:
    """Normalize provider model lists from the LiteLLM catalog snapshot."""
    return normalize_available_models(provider_models)


def _load_bundled_model_snapshot() -> dict[str, list[str]]:
    """Load the packaged LiteLLM model catalog when it is available."""
    return load_model_snapshot()


def get_config_path() -> Path:
    """Get path to user config file."""
    config_dir = get_state_dir()
    config_dir.mkdir(exist_ok=True)
    return config_dir / CONFIG_FILENAME


def load_config(*, suppress_errors: bool = False) -> dict[str, str]:
    """Load existing configuration."""
    config_path = get_config_path()
    loaded_config = {}

    if config_path.exists():
        try:
            with config_path.open(encoding="utf-8") as f:
                loaded_config.update(parse_config_env_lines(f))
        except (OSError, UnicodeError) as error:
            if suppress_errors:
                return {}
            raise ConfigurationError(
                f"Failed to read configuration from {config_path}: {error}"
            ) from error

    return loaded_config


def save_config(
    new_config: dict[str, str],
    *,
    console: Console | None = None,
) -> None:
    """
    Save configuration to file, preserving existing keys.

    Args:
        new_config: Dictionary of new configuration values to merge/update.
    """
    active_console = _resolve_console(console)
    config_path = get_config_path()
    current_config = load_config(suppress_errors=True)

    current_config.update(new_config)
    for key in LEGACY_CONFIG_KEYS:
        current_config.pop(key, None)

    # Ensure file exists and set restrictive permissions (owner-only read/write)
    config_path.touch(exist_ok=True)
    config_path.chmod(0o600)

    with config_path.open("w", encoding="utf-8") as f:
        f.write("# notewise Configuration\n")
        f.write("# Generated by notewise setup wizard\n\n")

        priority_keys = [
            "DEFAULT_MODEL",
            "OUTPUT_DIR",
            "MAX_CONCURRENT_VIDEOS",
        ]
        for key in priority_keys:
            if key in current_config:
                f.write(f"{key}={current_config[key]}\n")

        for key, value in sorted(current_config.items()):
            if key not in priority_keys:
                f.write(f"{key}={value}\n")

    active_console.print(
        f"\n[green]✓[/green] Configuration saved to: [cyan]{config_path}[/cyan]"
    )


def show_current_config(*, console: Console | None = None) -> dict[str, str]:
    """Display the current config in a read-only, masked form."""
    from rich.table import Table

    active_console = _resolve_console(console)
    config_path = get_config_path()
    try:
        current_config = load_config()
    except ConfigurationError as error:
        active_console.print(f"[red]{error}[/red]")
        return {}

    if not current_config:
        active_console.print(
            f"[yellow]No configuration found at {config_path}.[/yellow]"
        )
        return {}

    table = Table(title="Current Configuration", border_style="cyan")
    table.add_column("Key", style="bold cyan", no_wrap=True)
    table.add_column("Value")

    for key in sorted(current_config):
        value = current_config[key]
        if "KEY" in key or "TOKEN" in key or "SECRET" in key:
            value = mask_secret(value, suffix=" (set)")
        table.add_row(key, value)

    active_console.print(f"[dim]Config:[/dim] {config_path}")
    active_console.print(table)
    return current_config


def get_available_models(*, console: Console | None = None) -> dict[str, list[str]]:
    """Load setup-ready models from the bundled snapshot or LiteLLM metadata."""
    bundled_models = _load_bundled_model_snapshot()
    if bundled_models:
        return bundled_models

    return _load_litellm_models(console=console)


def _load_litellm_models(*, console: Console | None = None) -> dict[str, list[str]]:
    """Fetch available models from LiteLLM when the bundled snapshot is absent."""
    active_console = _resolve_console(console)
    try:
        from litellm import model_cost, model_list

        provider_models: dict[str, list[str]] = {}

        candidate_models = {*model_list, *model_cost}
        candidate_models.discard("sample_spec")

        for model in candidate_models:
            if not isinstance(model, str) or not model:
                continue
            metadata = _get_model_metadata(model, model_cost)
            provider = _classify_provider(metadata)
            if provider is None:
                continue
            if not _is_setup_safe_model(model, metadata):
                continue

            if provider not in provider_models:
                provider_models[provider] = []
            provider_models[provider].append(model)

        return _normalize_available_models(provider_models)

    except Exception as e:
        active_console.print(
            f"[yellow]⚠ Could not fetch models from LiteLLM: {e}[/yellow]"
        )
        active_console.print("[yellow]Using fallback model list...[/yellow]")
        return _normalize_available_models({})


def _get_model_metadata(
    model: str,
    model_cost: dict[str, dict[str, Any]],
) -> dict[str, Any]:
    """Return normalized LiteLLM metadata for a model when available."""
    return get_model_metadata(model, model_cost)


def _classify_provider(metadata: dict[str, Any]) -> str | None:
    """Map a model to one of the setup providers using LiteLLM provider metadata."""
    return classify_provider(metadata)


def _is_setup_safe_model(model: str, metadata: dict[str, Any]) -> bool:
    """Return True when a model is safe to show in setup."""
    return is_setup_safe_model(model, metadata)


def _prompt_positive_int(
    prompt: str,
    default: str,
    *,
    console: Console | None = None,
) -> str:
    """Prompt until the user enters a positive integer string."""
    from rich.prompt import Prompt

    active_console = _resolve_console(console)
    while True:
        value = Prompt.ask(prompt, default=default).strip()
        if value.isdigit() and int(value) >= 1:
            return value
        active_console.print(
            "[red]Please enter a whole number greater than or equal to 1.[/red]"
        )


def select_provider(
    available_models: dict[str, list[str]],
    *,
    console: Console | None = None,
) -> str:
    """Interactive provider selection."""
    from rich.prompt import Prompt
    from rich.table import Table

    active_console = _resolve_console(console)
    active_console.print("\n[bold cyan]Select LLM Provider:[/bold cyan]\n")

    table = Table(show_header=True, header_style="bold magenta")
    table.add_column("#", style="dim", width=4)
    table.add_column("Provider", style="cyan")
    table.add_column("Models Available", style="dim")

    providers_list = []
    for prov_key in PROVIDER_CONFIG:
        if prov_key in available_models:
            providers_list.append(prov_key)

    for i, provider_key in enumerate(providers_list, 1):
        config_data = PROVIDER_CONFIG[provider_key]
        model_count = len(available_models.get(provider_key, []))
        table.add_row(str(i), config_data["name"], f"{model_count} models")

    active_console.print(table)
    active_console.print(f"\n[dim]Total providers: {len(providers_list)}[/dim]")

    while True:
        choice = Prompt.ask(
            "\nSelect provider",
            choices=[str(i) for i in range(1, len(providers_list) + 1)],
        )
        return providers_list[int(choice) - 1]


def select_model(
    provider_key: str,
    available_models: dict[str, list[str]],
    *,
    console: Console | None = None,
) -> str:
    """Interactive model selection."""
    from rich.prompt import Prompt
    from rich.table import Table

    active_console = _resolve_console(console)
    provider_config = PROVIDER_CONFIG[provider_key]
    models = available_models.get(provider_key, [])

    if not models:
        active_console.print(
            f"[yellow]No models found for {provider_config['name']}[/yellow]"
        )
        return f"{provider_key}/default"

    active_console.print(
        f"\n[bold cyan]Select {provider_config['name']} Model:[/bold cyan]\n"
    )
    active_console.print(f"[dim]Showing {len(models)} available models[/dim]\n")

    page_size = 20
    current_page = 0

    while True:
        start_idx = current_page * page_size
        end_idx = min(start_idx + page_size, len(models))
        page_models = models[start_idx:end_idx]

        table = Table(show_header=True, header_style="bold magenta")
        table.add_column("#", style="dim", width=4)
        table.add_column("Model", style="green")

        for i, model in enumerate(page_models, start_idx + 1):
            model_display = model
            if "flash" in model.lower() or "mini" in model.lower():
                model_display = f"{model} [dim](fast)[/dim]"
            elif (
                "pro" in model.lower()
                or "turbo" in model.lower()
                or "sonnet" in model.lower()
            ):
                model_display = f"{model} [dim](powerful)[/dim]"

            table.add_row(str(i), model_display)

        active_console.print(table)

        total_pages = (len(models) + page_size - 1) // page_size
        active_console.print(
            f"\n[dim]Page {current_page + 1}/{total_pages} | "
            f"Showing {start_idx + 1}-{end_idx} of {len(models)} "
            f"models[/dim]"
        )

        if total_pages > 1:
            active_console.print(
                "[dim]Type 'n' for next page, 'p' for previous page, "
                "or model number to select[/dim]"
            )

        choice = Prompt.ask("\nSelect model (or n/p for navigation)")

        if choice.lower() == "n" and current_page < total_pages - 1:
            current_page += 1
            active_console.clear()
            active_console.print(
                f"\n[bold cyan]Select {provider_config['name']} Model:[/bold cyan]\n"
            )
            continue
        elif choice.lower() == "p" and current_page > 0:
            current_page -= 1
            active_console.clear()
            active_console.print(
                f"\n[bold cyan]Select {provider_config['name']} Model:[/bold cyan]\n"
            )
            continue
        elif choice.isdigit() and 1 <= int(choice) <= len(models):
            selected = models[int(choice) - 1]

            if (
                provider_key == "gemini"
                and not selected.startswith("gemini/")
                and not selected.startswith("vertex_ai/")
            ):
                return f"gemini/{selected}"

            return selected

        active_console.print(
            "[red]Invalid choice. Enter a model number or use n/p to navigate.[/red]"
        )


def get_api_key(
    provider_key: str,
    existing_key: str | None = None,
    *,
    console: Console | None = None,
) -> str:
    """Prompt for API key."""
    from rich.prompt import Confirm, Prompt

    active_console = _resolve_console(console)
    provider = PROVIDER_CONFIG[provider_key]

    active_console.print(
        f"\n[bold yellow]API Key Required:[/bold yellow] {provider['name']}"
    )
    active_console.print(
        f"[dim]Get your API key from:[/dim] "
        f"[link={provider['api_url']}]{provider['api_url']}[/link]\n"
    )

    if existing_key:
        masked = (
            f"{existing_key[:8]}...{existing_key[-4:]}"
            if len(existing_key) > 12
            else "***"
        )
        use_existing = Confirm.ask(f"Use existing key ({masked})?", default=True)
        if use_existing:
            return existing_key

    while True:
        api_key = Prompt.ask("Enter your API key", password=True)
        if api_key and len(api_key) > 10:
            return api_key
        active_console.print("[red]Invalid API key. Please try again.[/red]")


def run_setup_wizard(
    force: bool = False,
    console: Console | None = None,
) -> dict[str, str]:
    """Run interactive setup wizard."""
    from rich.panel import Panel
    from rich.prompt import Confirm, Prompt

    active_console = _resolve_console(console)
    active_console.print(
        Panel(
            "[bold cyan]🎓 notewise Setup Wizard[/bold cyan]\n\n"
            "Configure your LLM provider and API keys\n"
            "[dim]Bundled LiteLLM model catalog for fast setup[/dim]",
            border_style="cyan",
            expand=False,
        )
    )

    current_config = load_config()

    if current_config and not force:
        active_console.print("\n[yellow]Existing configuration found.[/yellow]")
        reconfigure = Confirm.ask("Do you want to reconfigure?", default=False)
        if not reconfigure:
            active_console.print("[green]Using existing configuration.[/green]")
            return current_config

    active_console.print("\n[cyan]Loading available models...[/cyan]")
    available_models = get_available_models(console=active_console)
    active_console.print(
        f"[green]✓ Found {sum(len(m) for m in available_models.values())} "
        f"models across {len(available_models)} providers[/green]"
    )

    provider_key = select_provider(available_models, console=active_console)
    model = select_model(provider_key, available_models, console=active_console)

    provider_info = PROVIDER_CONFIG[provider_key]
    env_var = provider_info.get("env_var")
    api_key = None
    if provider_info.get(
        "auth_type", AUTH_TYPE_API_KEY
    ) == AUTH_TYPE_API_KEY and isinstance(
        env_var,
        str,
    ):
        existing_key = current_config.get(env_var)
        api_key = get_api_key(provider_key, existing_key, console=active_console)
    elif provider_info.get("auth_type") == AUTH_TYPE_OAUTH_DEVICE:
        active_console.print(
            f"\n[bold yellow]OAuth Device Flow:[/bold yellow] {provider_info['name']}"
        )
        active_console.print(
            "[dim]No API key is required for this provider. LiteLLM will show a "
            "device code on first use and store provider tokens locally. Existing "
            "API keys in config are preserved for future provider switches.[/dim]"
        )
        if Confirm.ask(OAUTH_SETUP_RUN_PROMPT, default=True):
            _load_oauth_dependencies()
            if run_oauth_login is not None and not run_oauth_login(
                provider_key,
                console=active_console,
            ):
                active_console.print(
                    "[red]OAuth login failed or was cancelled. Setup stopped.[/red]"
                )
                return current_config

    active_console.print("\n[bold cyan]Output Directory:[/bold cyan]")
    default_output = str(Path.cwd() / Path(DEFAULT_OUTPUT_DIR))
    if "OUTPUT_DIR" in current_config:
        default_output = current_config["OUTPUT_DIR"]

    output_dir = Prompt.ask("Where should notes be saved?", default=default_output)

    active_console.print("\n[bold cyan]Concurrency:[/bold cyan]")
    default_concurrency = current_config.get(
        "MAX_CONCURRENT_VIDEOS",
        str(DEFAULT_MAX_CONCURRENT_VIDEOS),
    )
    concurrency = _prompt_positive_int(
        "Max concurrent videos to process?",
        default_concurrency,
        console=active_console,
    )

    new_config = {
        "DEFAULT_MODEL": model,
        "OUTPUT_DIR": output_dir,
        "MAX_CONCURRENT_VIDEOS": concurrency,
    }
    if isinstance(env_var, str) and api_key:
        new_config[env_var] = api_key

    save_config(new_config, console=active_console)

    active_console.print("\n[bold green]✓ Setup complete![/bold green]")
    active_console.print(
        Panel(
            f"[dim]Selected model:[/dim] [cyan]{model}[/cyan]\n"
            f"[dim]Configuration saved to:[/dim] [cyan]{get_config_path()}[/cyan]\n\n"
            "[bold]Next Steps:[/bold]\n"
            'Run: [green]notewise process "URL"[/green]',
            title="🎉 Ready to go",
            border_style="green",
        )
    )

    current_config.update(new_config)
    for key in LEGACY_CONFIG_KEYS:
        current_config.pop(key, None)
    return current_config
